### PR TITLE
Better Memory Pack Type 7 check + Page Buffer change + Memory Map fix

### PR DESCRIPTION
**Pull request by LuigiBlood**
Reverts Type 7 check from BSXFlash and puts it in nall instead (I completely forgot nall wasn't just always a replacement for most functions)

Also puts Page Buffer (or Vendor Info) at both 0x7F00 and 0xFF00.
Mostly because SD Gundam G-NEXT Memory Pack ROM has one at 0x7F00.

### CODE REVIEW

**Comment by LuigiBlood** [comment]
I just got custom size support for Memory Packs (just in case, really), should I add that to the PR?

**Comment by awjackson** [comment]
Are you sure about the change to the vendor info mapping? I wouldn't base too much on what the ROM memory packs contain--SD Gundam never even tries to read that vendor info block.

**Comment by LuigiBlood** [comment]
I don't think any games should have errors with this, they always use 0x75 to read that and then reset to normal after reading it.

**Comment by LuigiBlood** [comment]
Fixed BSCLoROM memory map (fixes RPG Maker 2, Sound Novel Maker and Derby Stallion 96's Memory Pack detection)

Also, for future reference: Do not try to change 0x1A from the Memory Pack Vendor Info (unless it is not Flash), if you don't want an infinite looping check when trying to boot a game on BS-X.

**Pull request merged**
