### PR TITLE
OS X Build

### PR DESCRIPTION
**Pull request by Optiroc**
- nall/dl looks inside app bundle for dylibs on OS X build
- "make all" also builds plugins
- "make install" on OS X builds plugins, copies them to bundle frameworks, and moves bundle to /Applications

### CODE REVIEW

**Comment by CarterLi** [comment]
Well done. But why do you comment snesfilter out?
Instead of moving bundle to ```/Applications``` directly, I suggest that you should make a dmg package like other commercial apps do.

**Comment by Optiroc** [comment]
> Well done. But why do you comment snesfilter out?

One of the filters depend on OpenMP, which isn't available to Clang as of now. There's more disussion about that in your original issue. 

> Instead of moving bundle to /Applications directly, I suggest that you should make a dmg package like other commercial apps do.

Well, that would be a task for "make installer" or something like that. 

Also, this is really quite far removed from a "commercial app" – it's a SNES debugging emulator, and I really don't think its users would be too interested in an installer package. For archiving releases, simply zipping up the app bundle is the cleanest solution I think.

**Comment by devinacker** [comment]
The plugin can still be built without OpenMP afaik (all it's needed for is a single #pragma, which is otherwise ignored), it just won't take advantage of it for multithreading when using hq2x. Given that that filter seems to be on the way out in upstream anyway, I think it's okay to leave snesfilter in for OS X otherwise.

**Comment by CarterLi** [comment]
> Also, this is really quite far removed from a "commercial app" – it's a SNES debugging emulator
I'm sorry for my bad words.
What I want to say is that making a dmg package may help people _install_ their apps, despite the app being commercial or not.

**Pull request merged**
