### PR TITLE
[BS-X] Satellaview Signal + Memory Pack changes

### PR DESCRIPTION
**Pull request by LuigiBlood**
**It's merged.**

Done:
- Satellaview Signal Support
- 1MB Empty Memory Pack loaded by default
- Memory Pack Saving option
- Allow custom path for Satellaview data files (could probably be done better, such as the default folder name)

Todo:
- Allow custom time & date (that's actually a feature people would want)

### CODE REVIEW

**Comment by LuigiBlood** [comment]
Just added Memory Pack save option (doesn't disappear but it's easy to not make it do anything when it's not a game with Memory Pack support).
(Also accidentally committed my modified makefile for 32-bit compiling which I reverted quickly)

**Comment by devinacker** [comment]
Some thoughts while I'm at work:

Would it be good to add an additional line to the "load BS-X cartridge" dialog to specify the data path instead of using hardcoded `./bsxdat`?

Also, for the "save memory pack" menu item, it would probably help to have something like this at the end of `Utility::modifySystemState` (in ui-qt/utility/system-state.cpp):

`mainWindow->system_saveMemoryPack->setVisible(SNES::cartridge.loaded() && SNES::cartridge.has_bsx_slot());`

and then make it initially hidden after adding it to the menu.

**Comment by LuigiBlood** [comment]
- An additional line for load BS-X cartridge would be a bad idea, there are actually other games making use of the Satellaview (only two, Derby Stallion 96 and Shigesato Itoi's Bass Fishing No. 1), that needs to be taken into account.

- About the path itself, my issue is to actually set the path on the config file and link it with an external config to the core. What I did simply crashed bsnes-plus on boot. I should try with an array of 256 chars though, perhaps that can work better...

- I was not familiar with setVisible and stuff so I just added by default for the time being, but that seems doable just fine, I can do that.

**Comment by LuigiBlood** [comment]
Ah damn, now there's a conflict because I didn't have an up to date source...

**Comment by devinacker** [comment]
Don't worry about the conflict, I can merge the stuff manually once it's ready (and maybe squash a few of the commits to clean up the makefile mistake, etc.)

Once I get home from work I'll give everything a try with the data files you sent me.

**Pull request closed without merging**
