### PR TITLE
An addition to the cheatfinder interface to make it easy to compare with previous values etc.

### PR DESCRIPTION
**Pull request by Grieverheart**
I have added a simple radio selection to the cheatfinder interface that gives the user the ability to compare current values to previous ones, to the value at a certain address, or to a fixed value. This is standard in debugging emulators such as FCEUX, and makes it easy to discover values that have (or haven't) changed.

Note that I made some changes to the Makefile. Since I have both versions of QT on my PC, I had to specify that it should use QT4.

### CODE REVIEW

**Comment by undisbeliever** [comment]
> Note that I made some changes to the Makefile. Since I have both versions of QT on my PC, I had to specify that it should use QT4.

That is not going to work in Windows. The Qt windows 4.8.6 Installer only creates `moc.exe`, not `moc-qt4.exe`

**Comment by Grieverheart** [comment]
> That is not going to work in Windows. The Qt 4.8.6 windows installer only creates moc.exe, not moc-qt4.exe

I made the change so I could compile on my machine, but wasn't sure how to remove the commit when doing the pull request.

If possible, this change should of course be skipped, but the problem remains (I can open a separate issue on that).

**Comment by devinacker** [comment]
> I made the change so I could compile on my machine, but wasn't sure how to remove the commit when doing the pull request.

Generally, you should create a git branch with just the commits you want, and then open the pull request using that branch instead of the master branch. I can just manually merge the one commit for the cheat finder, so it's not a huge deal this time.

re: makefile changes - at a glance, it seems like the ideal/correct solution is to install the `qtchooser` utility (which should create some symlinks at `/usr/bin/moc`, etc.) and then `export QT_SELECT=qt4` before building. If that works, I'll update the build instructions to include that.

**Comment by undisbeliever** [comment]
I compile bsnes-plus on linux with `make moc=moc-qt4 rcc=rcc-qt4` but that may be a mouthful.

**Comment by devinacker** [comment]
Merged the cheat finder changes, with a couple of small tweaks.

**Pull request closed without merging**
