### PR TITLE
OSX build

### PR DESCRIPTION
**Pull request by Optiroc**
Added deployment target flags and updated README with instructions for Qt4 on OSX 10.12. Now builds on latest OSX.

### CODE REVIEW

**Comment by devinacker** [comment]
merged, thanks.

Is there any specific reason -mmacosx-version-min is set to 10.10 instead of e.g. 10.7?

**Comment by Optiroc** [comment]
Hmm, that change has been laying around on my disk for several months, so I don't quite remember. I know that I kept bumping the setting until it was able to build though. I'll look into the details!

**Comment by Optiroc** [comment]
For -mmacosx-version-min 10.8 and below <initializer_list> seems not to be available. Setting it to 10.9 does seem to work though.

```
In file included from /usr/local/Cellar/qt/4.8.7_2/include/QtCore/qobject.h:50:
/usr/local/Cellar/qt/4.8.7_2/include/QtCore/qlist.h:55:10: fatal error: 
      'initializer_list' file not found
#include <initializer_list>
```

**Comment by devinacker** [comment]
What happens if you add `-std=c++0x` and `-stdlib=libc++` to the flags when using 10.7 or 10.8? I remember that being necessary when I was helping someone build one of my other Qt projects on OS X a while ago.

Then again, specifying a newer minimum OS version may be a better idea. I have no idea what the distribution of OS X versions among potential users is like.

**Comment by Optiroc** [comment]
Actually now (using Apple LLVM version 8.0.0 (clang-800.0.42.1)) compilation goes through without specifying `mmacosx-version-min` or `stdlib`. So for anyone rolling his/her own binary omitting these flags seems to be the best option. As for building a binary for distribution, I'm guessing 10.9 and libc++ is good. Although now that Qt4 is deprecated (?) I'm not sure if a user friendly binary distribution is anything to go for anyway.

**Pull request merged**
