### PR TITLE
Show tile address on click in VRAM viewer.

### PR DESCRIPTION
**Pull request by mziab**
A tentative implementation of showing the tile address on click in the VRAM viewer.

### CODE REVIEW

**Comment by devinacker** [comment]
Looks mostly okay to me.

Was VramViewer::Canvas changed to a non-member class for any particular reason? I'd prefer not to do anything like that with the original class definitions unless needed.

**Comment by mziab** [comment]
I remember there being a specific reason why I did it this way, but I can't recall the details off the top of my head. I will look into it and get back to you on that.

**Comment by mziab** [comment]
Right, the reason is the infoChanged signal I introduced. I cannot declare a signal with Canvas declared as a struct and moc doesn't support meta object features in nested classes, so that's not an option either. Emitting that signal seemed like the cleanest solution at the time. 

On an unrelated note, the code relies on the VRAM viewer displaying 64 tiles in one row.

**Comment by devinacker** [comment]
Signals and slots can be declared in structs as long as they inherit QObject and use the Q_OBJECT macro like normal (because structs in C++ *are* classes but with members being public by default). 

I wasn't aware of the restriction on nested classes though, so I guess that's fine. I'd probably keep it as a struct and give it a less generic name to make up for no longer being nested (VramCanvas or something?)

**Comment by mziab** [comment]
Applied your suggestions and fixed one indentation error along the way.

**Pull request merged**
