### PR TITLE
Add support for filter xBRZ ( with other small improvements )

### PR DESCRIPTION
**Pull request by CarterLi**
With [the original authur's permission](https://github.com/devinacker/bsnes-plus/pull/25#issuecomment-111996309), I'd like to open this again ( some small improvements have been done after [my previous PR is closed](https://github.com/devinacker/bsnes-plus/pull/25) )

image

### CODE REVIEW

**Comment by ADormant** [comment]
Can it be merged? @devinacker

**Comment by devinacker** [comment]
Soon. I'm going to add it as a replacement for HQ2x, so that I can get rid of the dependency on OpenMP while also having a decent replacement for it.

**Comment by devinacker** [comment]
screenshot

Did you make any changes to the filter between taking that screenshot and making the pull request? I finally added it to a local build and am getting this very noticeable discoloration on every game.

Also, the filter has _extremely_ poor performance compared to other filters when using Direct3D (20 FPS on my machine) and DirectDraw (5(!!) FPS) for video. I originally considered using this filter as a replacement for HQ2x that didn't rely on OpenMP to perform well, but it seems like this filter would need the same parallelization to actually work well across all video drivers.

**Comment by CarterLi** [comment]
> Did you make any changes to the filter between taking that screenshot and making the pull request? 

No, I didn't.
> I finally added it to a local build and am getting this very noticeable discoloration on every game.

May due to the difference of OS. I have no chance to test it on windows yet. Please try to define/undefine [R5G6B5 in xbrzfilter.cpp](https://github.com/devinacker/bsnes-plus/pull/27/files#diff-574d8def0aeebfe434d25ea383b971b2R8) then see if it's fixed.

> Also, the filter has extremely poor performance compared to other filters when using Direct3D (20 FPS on my machine) and DirectDraw (5(!!) FPS) for video.

Nope. As you can see in my screenshot, I got 61fps with xBRZ3x enabled on OSX, although bsnes-plus lags more on OSX __even without any filters enabled__.
As I said in my old PR, many emulators already have xBRZ support, and they perform well on Windows . Performance should not be a problem of xBRZ.

**Comment by devinacker** [comment]
Okay, removing RGB565 fixed the coloration issue. 

I'd still like to investigate the DirectX performance problems before merging, though.

**Comment by CarterLi** [comment]
> I'd still like to investigate the DirectX performance problems before merging, though.

After having a hard time building bsnes-plus with msys2, I finally have a chance to test this on Windows.
As @devinacker said, I got poor preformance using DirectX video core ( about 42fps ), which is unacceptable.
On the other hand, I got 60fps using OpenGL & Qt-Raster core ( about 100 fps with ```Sync Audio``` disabled ), have no idea why a video core that matters.
image

Any idea @Zenju?

**Comment by mrehkopf** [comment]
I know next to nothing about this but could it be that the particular colorspace conversion is expensive using DirectX?

**Comment by devinacker** [comment]
I get the same thing (good performance with OpenGL and Qt-Raster, poor performance with Direct3D, and with DirectDraw it's completely unusable). Other people who tested my builds had similar results.

I hacked up a multithreaded version of the filter using Qt threads which got Direct3D up to 55-60 FPS in most cases, but DirectDraw still got 3-5 FPS all the time, and OpenGL seemed to somehow get slower, which is a bit baffling.

@mrehkopf My understanding is that the snesfilter plugin (which is where this code lives) does all its work in software; the DirectX / OpenGL stuff just puts the results inside the window (and does scaling / aspect ratio / scanline effects as well? I don't really remember).

**Comment by Zenju** [comment]
@ CarterLi: To get the best performance out of xBRZ, the scaling needs to run multithreaded with slices not smaller than 8 rows. I suggest 16 rows per task. Speaking of tasks, the simplest integration is done by using a task scheduler like PPL (or TBB for cross-platform).
With this setup the xBRZ scaling time should go down by 1 / <number of cores> compared to single-threaded use. If there is noticeable overhead, something is not setup quite right.

**Comment by ADormant** [comment]
So what happened with this PR?

**Comment by ADormant** [comment]
So what happened with this PR?

**Comment by devinacker** [comment]
I'm still willing to merge it if the major performance issues are fixed.

**Comment by CarterLi** [comment]
I'm still following the development of xbrz, and use it myself.
bsnes+ won't compile on my mac for months, so I can't test my plugin on the latest version.
I don't bother to fire an issue here, since the errors don't seem to be bsnes+ itself and few people care about mac.
```
clang++ -xc -std=gnu99 -I. -Isnes -O3 -fomit-frame-pointer -DNDEBUG -march=native -DNDEBUG -Wno-switch -Wno-absolute-value -Wno-parentheses -march=native -DPROFILE_COMPATIBILITY -DDEBUGGER -c libco/libco.c -o obj/libco.o
In file included from libco/libco.c:22:
libco/amd64_gcc.c:135:17: error: parameter references not allowed in naked functions
    : [to] "r" (to), [from] "r" (from)
                ^
libco/amd64_gcc.c:66:6: note: attribute is here
void NAKED co_switch(cothread_t to) {
     ^
libco/amd64_gcc.c:61:34: note: expanded from macro 'NAKED'
    #define NAKED __attribute__((naked))
                                 ^
libco/amd64_gcc.c:67:3: error: non-ASM statement in naked function is not supported
  register cothread_t from __asm__("rdx") = co_active_handle;
  ^
libco/amd64_gcc.c:66:6: note: attribute is here
void NAKED co_switch(cothread_t to) {
     ^
libco/amd64_gcc.c:61:34: note: expanded from macro 'NAKED'
    #define NAKED __attribute__((naked))
                                 ^
```

**Comment by Optiroc** [comment]
I had those errors with the clang version supplied with the Xcode 7 betas, but they cleared up at some point. There were some include/linking errors remaining that I just fixed on my fork: https://github.com/Optiroc/bsnes-plus/commit/8ba7c6c4e003f229d9b212d976d4a07ed9579dd4

**Comment by devinacker** [comment]
@Optiroc merged, thanks.

@CarterLi Can you try building with a newer xcode/clang and see what happens?

**Comment by Optiroc** [comment]
Cool. Note to anyone who wants to build on OS X: I've only tested with $qtpath present in my environment, and I suspect the "code path" in the makefile for a blank qtpath may be broken too.

**Comment by CarterLi** [comment]
@Optiroc No, it doesn't help. Same errors generated.
XCode Version 7.1 (7B91b), installed from AppStore, with xcode-select --install executed

**Comment by Optiroc** [comment]
I had a look at the compare view: https://github.com/devinacker/bsnes-plus/compare/master...Optiroc:master

So... I guess I just took a stab in the dark and defined the NAKED macro to nothing, and it worked. (:

**Comment by CarterLi** [comment]
` So... I guess I just took a stab in the dark and defined the NAKED macro to nothing, and it worked. (: `

Thank you. Now it compiles again

**Comment by devinacker** [comment]
@CarterLi @Optiroc I'm going to file an issue upstream since it seems this was due to a somewhat recent change in llvm.

In the meantime, try building with LIBCO_NO_INLINE_ASM defined in order to use the (hopefully still supported) amd64.c instead of amd64_gcc.c

**Comment by ADormant** [comment]
Are those performance issues still present?

**Comment by devinacker** [comment]
Probably, since there haven't really been any changes to the branch as of late.

**Comment by CarterLi** [comment]
I released (a version)[https://github.com/CarterLi/bsnes-plus/releases] for testing, OSX only.
I have no windows machine, so no windows version available.

**Comment by sharknnth** [comment]
I was wondering if there was any way to get this awesome version on Windows? 6xBRZ is a nice filter.

**Comment by sharknnth** [comment]
CaterLi, thanks for implementing this great filter, I managed to compile a Windows 32-bit build from your latest source code and yes just as previously has been mentioned, Direct3D has frame rate issues getting around 40 fps but OpenGL works very well. Here is the build I compiled[http://www40.zippyshare.com/v/onr6YO9L/file.html
](url)

**Comment by sharknnth** [comment]
CaterLi, thanks for implementing this great filter, I managed to compile a Windows 32-bit build from your latest source code and yes just as previously has been mentioned, Direct3D has frame rate issues getting around 40 fps but OpenGL works very well. Here is the build I compiled [http://www30.zippyshare.com/v/IBClEeWj/file.html](url)

**Comment by sharknnth** [comment]
I managed to compile a Windows 64-bit binary with an accuracy profile. There's naturally a speed boost over the 32-bit build and one of the bugs in Windows seems to lie in the creation of snesfilter.dll it makes some occasional effects just display a black screen until it has passed like the Rareware sequence in Donkey Kong Country and the opening screens of Doom. In the accuracy build it doesn't display xBRZ at all and in full screen with any filter. Here's the Windows 64 binary http://www52.zippyshare.com/v/DJWn43bm/file.html

**Comment by gilatino** [comment]
@sharknnth How I can use xbrz in windows?

**Comment by sharknnth** [comment]
@gilatino Go to settings then video filter then select xbrz from the same menu you can choose configure active filter and set it from anywhere between 2 and 6 times strength. You must be using bsnes.exe rather than bsnes-accuracy.exe as there are incompatibilities with the accuracy profile. Go to settings, advanced to make sure that you're using openGL for the best results.

**Comment by mrehkopf** [comment]
The "Video Filter" submenu in the Settings menu is missing for me. It's "Video Mode >" and then "[ ] Smooth Video Output" without the "Video Filter >" entry inbetween. Any pointers?

**Comment by devinacker** [comment]
You'll need snesfilter.dll to be built/present in order to have the Video Filter menu.

**Comment by mrehkopf** [comment]
snesfilter.dll is present in the binaries built by @sharknnth, yet no dice :) I didn't attempt rolling my own build yet.

**Comment by sharknnth** [comment]
@mrehkopf I've updated the link on the 64-bit build. You should get it here https://github.com/sharknnth/bsnes-plus/releases

**Comment by gilatino** [comment]
@sharknnth The binaries without xbrz on https://github.com/sharknnth/bsnes-plus/releases have the "Video Filter" submenu while those with xbrz don't have the "Video Filter" submenu on my computer.

**Comment by mrehkopf** [comment]
This happens to me too, even with the latest builds and after deleting AppData/Roaming/.bsnes. When I replace the snesfilter.dll with a "stock" one the menu appears but without the xbrz filter obviously.

**Comment by CarterLi** [comment]
Try removing the switch `-march=native` and rebuild the project. It's useful for personal use, but for distribution.

**Comment by sharknnth** [comment]
@CarterLi Thanks for that advice, I've just done that to the makefile and uploaded a new build (v073+6) and a bsnes-classic build I have going too with this fix, hopefully this helps.

**Comment by mrehkopf** [comment]
Works great now, thanks @sharknnth and @CarterLi :)

**Pull request closed without merging**
